Nexus-38367 - make charts more configurable
sonatype/nxrm3-ha-repository pull request #28
Opened 2023-10-30 10:43 UTC by bobotimi

2023-11-17 19:00 UTC, Mykyta approved these changes

2023-11-17 22:11 UTC, mpiggott approved these changes

2023-11-22 19:46 UTC, lisadurant requested changes

2023-11-22 19:46 UTC, lisadurant commented on nxrm-ha/README.md
> +| `statefulset.clustered`                                     | Determines whether or not Nexus Repository should be run in clustered/HA mode. When this is set to false, the search differences [here]
```suggestion
| `statefulset.clustered`                                     | Determines whether or not Nexus Repository should be run in clustered/HA mode. When this is set to false, the search differences [here](https://help.sonatype.com/repomanager3/planning-your-implementation/resiliency-and-high-availability/high-availability-deployment-options#HighAvailabilityDeploymentOptions-SearchFeatureDifferences) do not apply.                                                                                  | true                                                                                                                |
```

2023-11-24 16:04 UTC, merged