update readme
sonatype/nxrm3-ha-repository pull request #47
Opened 2024-01-15 17:34 UTC by bobotimi

2024-02-22 16:22 UTC, lisadurant requested changes
one minor punctuation/grammar thing

2024-02-22 16:22 UTC, lisadurant commented on nxrm-ha/README.md
> +| `statefulset.container.additionalEnv`                       | Additional environment variables for the Nexus Repository container. You can also use this setting to override a default env variable b
```suggestion
| `statefulset.container.additionalEnv`                       | Additional environment variables for the Nexus Repository container. You can also use this setting to override a default env variable by specifying the same key/name as the default env variable you wish override. Specify this as a block of name and value pairs (e.g., "<br/>additionalEnv:<br/>- name: foo<br/> value: bar<br/>- name: foo2<br/> value: bar2")                 | null                                                                                                                |
```

2024-06-03 12:47 UTC, lisadurant approved these changes

2024-06-03 12:50 UTC, vswaminathan777 approved these changes

2024-06-03 15:21 UTC, merged