Support external secret operator
sonatype/nxrm3-ha-repository pull request #66
Opened 2024-03-01 13:50 UTC by bobotimi

2024-08-15 15:03 UTC, jarcilac commented
@bobotimi, I was wondering if we should also include the new secrets file. since it should be treated as the license file.

2024-08-15 15:03 UTC, jarcilac approved these changes

2024-08-15 15:57 UTC, Devleooper approved these changes

2024-08-15 16:49 UTC, lisadurant requested changes

2024-08-15 16:49 UTC, lisadurant commented on nxrm-ha/values.yaml
> +      dbHostKey: host # the name of the key in the secret which contains your database host.
```suggestion
      providerSecretName: dbSecretName # The name of the AWS SecretsManager/Azure KeyVault/etc. secret
      dbUserKey: username #  The name of the key in the secret that contains your database username
      dbPasswordKey: password # The name of the key in the secret that contains your database password
      dbHostKey: host # The name of the key in the secret that contains your database host
```

2024-08-15 16:49 UTC, lisadurant commented on nxrm-ha/values.yaml
> +      adminPasswordKey: "nexusAdminPassword" # the name of the key in the secret which contains your nexus repository admin password
```suggestion
      providerSecretName: adminSecretName # The name of the AWS SecretsManager/Azure KeyVault/etc. secret
      adminPasswordKey: "nexusAdminPassword" # The name of the key in the secret that contains your nexus repository admin password
```

2024-08-15 16:49 UTC, lisadurant commented on nxrm-ha/values.yaml
> +      providerSecretName: nexus-repo-license.lic # The name of the AWS SecretsManager/Azure KeyVault etc secret which contains your Nexus Repository license
```suggestion
      providerSecretName: nexus-repo-license.lic # The name of the AWS SecretsManager/Azure KeyVault/etc. secret that contains your Nexus Repository license
```

2024-08-15 16:49 UTC, lisadurant commented on nxrm-ha/values.yaml
> +#                name: nexus-repository-deployment-sa # use same service account name as specified in serviceAccount.name
```suggestion
#                name: nexus-repository-deployment-sa # Use the same service account name as specified in serviceAccount.name
```

2024-08-15 16:49 UTC, lisadurant commented on nxrm-ha/values.yaml
> +#            name: nexus-repository-deployment-sa # use same service account name as specified in serviceAccount.name
```suggestion
#            name: nexus-repository-deployment-sa # Use the same service account name as specified in serviceAccount.name
```

2024-08-29 12:00 UTC, lisadurant approved these changes

2024-10-25 13:59 UTC, merged